Form tidak valid: <ul class="errorlist"><li>nama<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nama<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nama<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nama<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nama<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nama<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nama<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nama<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nama<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nama<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
Internal Server Error: /cuti/
Traceback (most recent call last):
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\UANG\Sistem Informasi\sistem_informasi\cuti\views.py", line 17, in cuti
    return render(request, 'cuti.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'tahunajaran' not found. 'tahunajaran' is not a valid view function or pattern name.
Internal Server Error: /tahun_ajaran/tahun_ajaran/tambah/
Traceback (most recent call last):
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\UANG\Sistem Informasi\sistem_informasi\tahun_ajaran\views.py", line 57, in tambah_tahunajaran
    return redirect('tahunajaran')
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Kuliah\Coding\Project\Sistem Informasi\env\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'tahunajaran' not found. 'tahunajaran' is not a valid view function or pattern name.
Internal Server Error: /tahun_ajaran/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "tahun_ajaran_tahunajaranmodel" does not exist
LINE 1: ..."tahun_ajaran_tahunajaranmodel"."created_at" FROM "tahun_aja...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\tahun_ajaran\views.py", line 16, in tahunajaran
    return render(request, 'tahunajaran.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "tahun_ajaran_tahunajaranmodel" does not exist
LINE 1: ..."tahun_ajaran_tahunajaranmodel"."created_at" FROM "tahun_aja...
                                                             ^

Form tidak valid: <ul class="errorlist"><li>semester<ul class="errorlist"><li>This field is required.</li></ul></li><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>semester<ul class="errorlist"><li>This field is required.</li></ul></li><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Internal Server Error: /mahasiswa/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column mahasiswa_mahasiswa.jurusan does not exist
LINE 1: ..._mahasiswa"."foto", "mahasiswa_mahasiswa"."nama", "mahasiswa...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 17, in mahasiswa
    return render(request, 'mahasiswa.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column mahasiswa_mahasiswa.jurusan does not exist
LINE 1: ..._mahasiswa"."foto", "mahasiswa_mahasiswa"."nama", "mahasiswa...
                                                             ^

Internal Server Error: /mahasiswa/mahasiswa/1111111111/detail/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 79, in detail_mahasiswa
    return render(request, 'mahasiswa_detail.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: mahasiswa_detail.html
Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Internal Server Error: /mahasiswa/mahasiswa/1111111111/detail/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 80, in detail_mahasiswa
    return render(request, 'detail_mahasiswa.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\joki\djangoProject\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'mahasiswa-list' not found. 'mahasiswa-list' is not a valid view function or pattern name.
Internal Server Error: /mahasiswa/mahasiswa/1111111111/detail/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 80, in detail_mahasiswa
    return render(request, 'detail_mahasiswa.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\joki\djangoProject\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'mahasiswa-list' not found. 'mahasiswa-list' is not a valid view function or pattern name.
Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>jurusan<ul class="errorlist"><li>This field is required.</li></ul></li><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>syarat_cuti<ul class="errorlist"><li>File extension �jpeg� is not allowed. Allowed extensions are: pdf.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>syarat_cuti<ul class="errorlist"><li>File extension �txt� is not allowed. Allowed extensions are: pdf.</li></ul></li></ul>
Internal Server Error: /mahasiswa/mahasiswa/1111111111/detail/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 79, in detail_mahasiswa
    return render(request, 'mahasiswa_detail.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: mahasiswa_detail.html
Form tidak valid: <ul class="errorlist"><li>jurusan<ul class="errorlist"><li>This field is required.</li></ul></li><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>jurusan<ul class="errorlist"><li>This field is required.</li></ul></li><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>jurusan<ul class="errorlist"><li>This field is required.</li></ul></li><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>jurusan<ul class="errorlist"><li>This field is required.</li></ul></li><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Internal Server Error: /mahasiswa/mahasiswa/tambah/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "jurusan" of relation "mahasiswa_mahasiswa" violates not-null constraint
DETAIL:  Failing row contains (987654321, uploads/profile/profile1_kLmy9KL.jpg, joko, L, banda aceh, 2023-08-22, Indonesia, affanianamara@gmail.com, jokowe, Aktif, 2019, 8, Islam, ga ada hehe, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 58, in tambah_mahasiswa
    form.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "jurusan" of relation "mahasiswa_mahasiswa" violates not-null constraint
DETAIL:  Failing row contains (987654321, uploads/profile/profile1_kLmy9KL.jpg, joko, L, banda aceh, 2023-08-22, Indonesia, affanianamara@gmail.com, jokowe, Aktif, 2019, 8, Islam, ga ada hehe, null).

Internal Server Error: /user_manage/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\user_manage\views.py", line 16, in user_list
    return render(request, 'user_list.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\joki\djangoProject\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'hapus_user' not found. 'hapus_user' is not a valid view function or pattern name.
Internal Server Error: /mahasiswa/mahasiswa/1111111111/edit/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 24, in edit_mahasiswa
    custom_user = CustomUser.objects.get(user=request.user)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 623, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: NIM, custom_groups, custom_user_permissions, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, nama, password, role, status, user_permissions, username
Internal Server Error: /mahasiswa/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 21, in mahasiswa
    mahasiswa_list = Mahasiswa.objects.filter(program_studi=jurusan)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'program_studi' into field. Choices are: agama, alamat, angkatan, beasiswa, doswal, email, foto, jk, jurusan, nama, nim, semester, status, tanggal_lahir, tempat_lahir
Internal Server Error: /pengajar/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\dosen_pengajar\views.py", line 18, in pengajar
    DosenPengajar_list = DosenPengajarModel.objects.filter(jurusan=jurusan)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'jurusan' into field. Choices are: agama, alamat, email, foto, jk, kelas, mata_kuliah_list, nama, nrp, prodi, status, tanggal_lahir, tempat_lahir
Internal Server Error: /pengajar/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\dosen_pengajar\views.py", line 18, in pengajar
    DosenPengajar_list = DosenPengajarModel.objects.filter(jurusan=jurusan)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'jurusan' into field. Choices are: agama, alamat, email, foto, jk, kelas, mata_kuliah_list, nama, nrp, prodi, status, tanggal_lahir, tempat_lahir
Internal Server Error: /pengajar/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\dosen_pengajar\views.py", line 18, in pengajar
    DosenPengajar_list = DosenPengajarModel.objects.filter(jurusan=jurusan)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'jurusan' into field. Choices are: agama, alamat, email, foto, jk, kelas, mata_kuliah_list, nama, nrp, prodi, status, tanggal_lahir, tempat_lahir
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 13, in krs
    return render(request, 'k.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: k.html
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (1, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 15, in krs
    krs.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (1, null).

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 11, in krs
    krs, created = KRS.objects.get_or_create(mahasiswa=user.mahasiswa)
  File "D:\joki\djangoProject\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'CustomUser' object has no attribute 'mahasiswa'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 11, in krs
    mahasiswa = user.mahasiswa  # Ubah ini sesuai hubungan antara CustomUser dan Mahasiswa
  File "D:\joki\djangoProject\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'CustomUser' object has no attribute 'mahasiswa'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 44, in pengisian_krs
    form.fields['nama_pengajar'].queryset =  matakuliah_list
KeyError: 'nama_pengajar'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 44, in pengisian_krs
    form.fields['nama_mata_kuliah'].queryset =  matakuliah_list
KeyError: 'nama_mata_kuliah'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 44, in pengisian_krs
    form.fields['mata_kuliah_pilihan'].choices = [(matkul.id, matkul.nama_mata_kuliah) for matkul in matakuliah_list]
KeyError: 'mata_kuliah_pilihan'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 44, in pengisian_krs
    form.fields['mata_kuliah_pilihan'].choices = [(matkul.id, matkul.nama_mata_kuliah) for matkul in matakuliah_list]
KeyError: 'mata_kuliah_pilihan'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 44, in pengisian_krs
    form.fields['mata_kuliah_pilihan'].choices = [(matkul.id, matkul.nama_mata_kuliah) for matkul in matakuliah_list]
KeyError: 'mata_kuliah_pilihan'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 44, in pengisian_krs
    form.fields['nama_matakuliah'].choices = [(matkul.id, matkul.nama_mata_kuliah) for matkul in matakuliah_list]
KeyError: 'nama_matakuliah'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 44, in pengisian_krs
    form.fields['nama_mata_kuliah'].choices = [(matkul.id, matkul.nama_mata_kuliah) for matkul in matakuliah_list]
KeyError: 'nama_mata_kuliah'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 40, in pengisian_krs
    return render(request, 'krs/create_krs.html', {'form': form})
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: krs/create_krs.html
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (2, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 33, in pengisian_krs
    krs = form.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (2, null).

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (3, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 33, in pengisian_krs
    krs = form.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (3, null).

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (4, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 33, in pengisian_krs
    krs = form.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (4, null).

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (5, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 33, in pengisian_krs
    krs = form.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (5, null).

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view krs.views.pengisian_krs didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view krs.views.pengisian_krs didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 44, in pengisian_krs
    return render(request, 'krs/create_krs.html', {'form': form})
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: krs/create_krs.html
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (6, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 35, in pengisian_krs
    krs.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (6, null).

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (7, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 35, in pengisian_krs
    krs.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (7, null).

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (8, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 35, in pengisian_krs
    krs.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "mata_kuliah_id" of relation "krs_krs" violates not-null constraint
DETAIL:  Failing row contains (8, null).

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 44, in pengisian_krs
    form.fields['nama_mata_kuliah'].queryset = matakuliah_list
KeyError: 'nama_mata_kuliah'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 44, in pengisian_krs
    form.fields['nama_mata_kuliah'].queryset = matakuliah_list
KeyError: 'nama_mata_kuliah'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 32, in pengisian_krs
    if form.is_valid():
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\forms.py", line 196, in errors
    self.full_clean()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\forms.py", line 435, in full_clean
    self._post_clean()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 479, in _post_clean
    self.instance = construct_instance(
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 83, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\fields\__init__.py", line 1035, in save_form_data
    setattr(instance, self.name, data)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<QuerySet [<MataKuliah: Pancasila>]>": "KRS.matakuliah" must be a "MataKuliah" instance.
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 32, in pengisian_krs
    if form.is_valid():
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\forms.py", line 196, in errors
    self.full_clean()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\forms.py", line 435, in full_clean
    self._post_clean()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 479, in _post_clean
    self.instance = construct_instance(
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 83, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\fields\__init__.py", line 1035, in save_form_data
    setattr(instance, self.name, data)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<QuerySet [<MataKuliah: Pancasila>]>": "KRS.matakuliah" must be a "MataKuliah" instance.
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 32, in pengisian_krs
    if form.is_valid():
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\forms.py", line 196, in errors
    self.full_clean()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\forms.py", line 435, in full_clean
    self._post_clean()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 479, in _post_clean
    self.instance = construct_instance(
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 83, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\fields\__init__.py", line 1035, in save_form_data
    setattr(instance, self.name, data)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<QuerySet [<MataKuliah: Pancasila>]>": "KRS.matakuliah" must be a "MataKuliah" instance.
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "nim" of relation "krs_krs" does not exist
LINE 1: INSERT INTO "krs_krs" ("nim", "nama_mahasiswa", "mahasiswa_i...
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 33, in pengisian_krs
    krs = form.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "nim" of relation "krs_krs" does not exist
LINE 1: INSERT INTO "krs_krs" ("nim", "nama_mahasiswa", "mahasiswa_i...
                               ^

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 34, in pengisian_krs
    krs.nim = request.user.nim  # Gantikan dengan atribut yang sesuai pada objek User
  File "D:\joki\djangoProject\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'CustomUser' object has no attribute 'nim'
Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "nim" of relation "krs_krs" does not exist
LINE 1: INSERT INTO "krs_krs" ("nim", "nama_mahasiswa", "mahasiswa_i...
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 36, in pengisian_krs
    krs.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "nim" of relation "krs_krs" does not exist
LINE 1: INSERT INTO "krs_krs" ("nim", "nama_mahasiswa", "mahasiswa_i...
                               ^

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "nim" of relation "krs_krs" does not exist
LINE 1: INSERT INTO "krs_krs" ("nim", "nama_mahasiswa", "mahasiswa_i...
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 36, in pengisian_krs
    krs.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "nim" of relation "krs_krs" does not exist
LINE 1: INSERT INTO "krs_krs" ("nim", "nama_mahasiswa", "mahasiswa_i...
                               ^

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "nim" of relation "krs_krs" does not exist
LINE 1: INSERT INTO "krs_krs" ("nim", "nama_mahasiswa", "mahasiswa_i...
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 36, in pengisian_krs
    krs.save()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "nim" of relation "krs_krs" does not exist
LINE 1: INSERT INTO "krs_krs" ("nim", "nama_mahasiswa", "mahasiswa_i...
                               ^

Internal Server Error: /krs/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "krs_krs" does not exist
LINE 1: INSERT INTO "krs_krs" ("nim", "nama_mahasiswa", "mahasiswa_i...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\sistem_informasi\krs\views.py", line 36, in pengisian_krs
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "krs_krs" does not exist
LINE 1: INSERT INTO "krs_krs" ("nim", "nama_mahasiswa", "mahasiswa_i...
                    ^

Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>semester<ul class="errorlist"><li>This field is required.</li></ul></li><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Mahasiswa with this Nim already exists.</li></ul></li></ul>
Form tidak valid: <ul class="errorlist"><li>nim<ul class="errorlist"><li>Ensure this value is less than or equal to 2147483647.</li></ul></li></ul>
Internal Server Error: /mahasiswa/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 35, in mahasiswa
    return render(request, 'mahasiswa.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^

Internal Server Error: /mahasiswa/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 34, in mahasiswa
    return render(request, 'mahasiswa.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^

Internal Server Error: /mahasiswa/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 34, in mahasiswa
    return render(request, 'mahasiswa.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^

Internal Server Error: /mahasiswa/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 35, in mahasiswa
    return render(request, 'mahasiswa.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^

Internal Server Error: /mahasiswa/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 35, in mahasiswa
    return render(request, 'mahasiswa.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^

Internal Server Error: /mahasiswa/
Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\joki\djangoProject\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\joki\djangoProject\sistem_informasi\mahasiswa\views.py", line 35, in mahasiswa
    return render(request, 'mahasiswa.html', context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\joki\djangoProject\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column mahasiswa_mahasiswa.user_id does not exist
LINE 1: SELECT "mahasiswa_mahasiswa"."user_id", "mahasiswa_mahasiswa...
               ^

